### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by mad42**
Bumped nostrum, ex_doc and credo versions.

Fixed Elixir 1.11 warnings like:
```shell
warning: Nostrum.Api.create_message!/2 defined in application :nostrum is used by the current application but the current application does not directly depend on :nostrum. To fix this, you must do one of:

  1. If :nostrum is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :nostrum is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :nostrum, you may optionally skip this warning by adding [xref: [exclude: Nostrum.Api]] to your "def project" in mix.exs
```

### CODE REVIEW

**Comment by jchristgit** [comment]
Thank you very much!

Judging from the Travis failure, we need to bump the default Elixir version in mix.exs, right?

**Comment by mad42** [comment]
@jchristgit, you welcome !
I'll bump it and see how it goes..

**Comment by mad42** [comment]
CI fails asking for Discord Token

```shell
09:30:19.456 [info]  Application nostrum exited: exited in: Nostrum.Application.start(:normal, [])
766    ** (EXIT) an exception was raised:
767        ** (RuntimeError) Please supply a token
768            (nostrum 0.4.5) lib/nostrum/application.ex:39: Nostrum.Application.check_token/1
769            (nostrum 0.4.5) lib/nostrum/application.ex:10: Nostrum.Application.start/2
770            (kernel 6.5.2) application_master.erl:277: :application_master.start_it_old/4
771** (Mix) Could not start application nostrum: exited in: Nostrum.Application.start(:normal, [])
772    ** (EXIT) an exception was raised:
773        ** (RuntimeError) Please supply a token
774            (nostrum 0.4.5) lib/nostrum/application.ex:39: Nostrum.Application.check_token/1
775            (nostrum 0.4.5) lib/nostrum/application.ex:10: Nostrum.Application.start/2
776            (kernel 6.5.2) application_master.erl:277: :application_master.start_it_old/4
777The command "mix test --cover" exited with 1.
```

**Comment by jchristgit** [comment]
Thank you 🙂

**Pull request merged**
